# Usamos Nginx para servir HTML estático
FROM nginx:alpine

# Copiamos el index.html al lugar donde Nginx lo sirve
COPY index.html /usr/share/nginx/html/index.html

# Exponemos el puerto 80
EXPOSE 80

# Comando por defecto (ya viene con Nginx)
CMD ["nginx", "-g", "daemon off;"]
